slug = "miranda-was-right"
title = "Miranda was right"
author = "ted"
value = 50
description = """It was recently discovered that a CY_LABS employee named Miranda once sighted a legendary gif at her hometown. Get us Miranda’s place of birth so we can search for it. Submit it as flag{<place of birth>}. (all lowercase, underscores as spaces) You can access the CY_Labs website [here](<link to CY_Labs site sql injection>)."""
tags = [ "sql" ]
files = []
flag = "flag{luna}"
enabled = true