slug = "postbin-2"
title = "Postbin 2"
author = "defund"
value = 40
description = """Everything seems to be rendered as raw text :(

The admin has a cookie containing the flag on this [postbin](http://acmcyber.com:10002). Report links you want the admin to visit [here](http://acmcyber.com:10000)."""
tags = ["xss"]
files = []
flag = "flag{escape_the_textarea}"
enabled = true
