slug = "attention-check-2"
title = "Attention Check 2"
author = "Peter"
value = 30
description = """Now that you have the authorization token for the [site](INSERT HERE), can you find a way to login as the administrator?"""
tags = ["nosql"]
files = []
flag = "flag{glad_you_were_paying_attention}"
enabled = true
