slug = "not-ccle"
title = "Not CCLE"
author = "Kimberly"
value = 20
description = """You're scrolling through r/ucla and come across a post "CCLE DOWN AGAIN?!" This reminds you that you have a project due and so you go to CCLE investigate yourself. It seems like although [the login page] (https://main.d2l1r1pl615xsh.amplifyapp.com/challenges/not-ccle) is up, you forgot your login info. Figure out the login before it's too late to turn in your assignment."""
tags = ["intro"]
files = []
flag = "flag{ccle_constantly_causing_login_errors}"
enabled = true
