slug = "secure-web-dev-quiz"
title = "Secure Web Dev Quiz!"
author = "Aarin"
value = 20
description = """Test your knowledge on all the cool secure web dev techniques we talked about during our workshop! Join us live for the Kahoot, or take our Google Form quiz [here](https://forms.gle/yCG85vcJVZBNXMEQ6)!
"""
tags = ["secure-web-dev"]
files = []
flag = "flag{spaghetti_token_gang}"
enabled = true
