slug = "trivia-2"
title = "Trivia 2"
author = "Kimberly"
value = 10
description = """Where was the birthplace of cookies? (Spaces are separated with underscores, all lowercase. Make sure to wrap the answer in flag{...})"""
tags = []
files = []
flag = "flag{netscape_communications}"
enabled = false
