id = 1
title = "Cyber Academy: Intro to Web"
short = "Intro to Web" 
date = "Thursday 1/14 7:00PM-9:00PM PT"
description = """CCLE is down again? I wonder why? Whether you are an impulsive online shopper, chat on Discord, pay your credit cards, or simply want CCLE to work, these web applications are handling your data. Come to Cyber’s first winter workshop to learn the basics of web hacking in preparation for our future workshops.
"""
link = ""
slides = ""
