slug = "tesla"
title = "Tesla"
author = "Kimberly"
value = 15
description = """My name is Jeff. Just kidding, Jeff is too sad crying in the corner with his measly $182.4B to ever dare to introduce himself again. My name is Elon, and as the richest man in the world, I'm now giving away free stocks exclusively at [this website](https://main.d2l1r1pl615xsh.amplifyapp.com/challenges/tesla). Flag format is flag{}"""
tags = ["intro"]
files = []
flag = "flag{babyX-Ash-A-12}"
enabled = true
