slug = "attention-check-1"
title = "Attention Check 1"
author = "Peter"
value = 30
description = """I think I found an older version of the CY_Labs [site](http://attention-check.acmcyber.com:10000/site). Maybe there is still useful information on [there]. Do you think you could obtain an access token?"""
tags = ["nosql"]
files = []
flag = "flag{always_see_what_you_have_been_given}"
enabled = true
