version: "3.9"
services:
  redis:
    image: redis
  level1:
    build: .
    ports:
      - "10001:3000"
    environment:
      - XSS_LEVEL=1
  level2:
    build: .
    ports:
      - "10002:3000"
    environment:
      - XSS_LEVEL=2
  level3:
    build: .
    ports:
      - "10003:3000"
    environment:
      - XSS_LEVEL=3
  level4:
    build: .
    ports:
      - "10004:3000"
    environment:
      - XSS_LEVEL=4
