slug = "getting-lit"
title = "Getting LIT"
author = "Jerry"
value = 30
description = """[Here's](http://getting-lit.acmcyber.com:10000/index.php) a website I made celebrating my last minute submission for an assignment! My cat would love it if you checked it out :)"""
tags = ["php"]
files = []
flag = "flag{php_with_a_chance_of_flags}"
enabled = true
