slug = "postbin-4"
title = "Postbin 4"
author = "defund"
value = 60
description = """In Google we trust. Hint: Look at the headers.

The admin has a cookie containing the flag on this [postbin](http://acmcyber.com:10003). Report links you want the admin to visit [here](http://acmcyber.com:10000)."""
tags = ["xss", "csp"]
files = []
flag = "flag{callbacks_to_the_rescue}"
enabled = true
